### PR TITLE
Several improvements for your nominatim module

### PR DESCRIPTION
**Pull request by iburadempa**
- polishing of code and documentation
- add few unittests; run them from the project home with:
  python -m unittest discover
- changed default Nominatim instance to
  http://open.mapquestapi.com/nominatim/v1
  to avoid overloading of openstreetmap
  (s. http://wiki.openstreetmap.org/wiki/Nominatim_usage_policy )
- add option osm_id plus osm_type to NominatimReverse
- add zoom aliases (NominatimReverse)
- add countrycodes selection
- add url options to choose Nominatim instance
- add NominatimException
- factor out the HTTP request to NominatimRequest
- fix lat==0 or lon==0 leading to no result
- fix URL encoding

### CODE REVIEW

**Comment by damianbraun** [comment]
thanks for help :)

**Comment by iburadempa** [comment]
hi damian,

do you have plans for further improvement of the nominatim module?

in my view it would be nice to have functions for extracting useful
information from the query results, in particular if there are many of them.

best,
ibu

**Comment by damianbraun** [comment]
Hi, this module works good enough for me. I use it only for my gpxseg
https://github.com/damianbraun/gpxseg project.

If you have time and willingness im happy for your improvements. Only thing
i will ask you is to commit more often (commit per feature). I consider it
good practise and try to do it myself.

About this functions. Do you mean something like getStreet(), getAdress()?
Which would return only specific strings or rather unicodes?

How u use this module?

**Comment by iburadempa** [comment]
On 07/10/2014 05:41 PM, damianbraun wrote:

> Hi, this module works good enough for me. I use it only for my gpxseg
> https://github.com/damianbraun/gpxseg project.

I see, you're using it for reverse geocoding and with data where you can
reasonably expect to get a good result.

> If you have time and willingness im happy for your improvements. Only thing
> i will ask you is to commit more often (commit per feature). I consider it
> good practise and try to do it myself.

Sure, I'll try. - Initially I was adapting it to my own needs only.

> About this functions. Do you mean something like getStreet(), getAdress()?
> Which would return only specific strings or rather unicodes?
> 
> How u use this module?

I have short texts containing valid addresses, invalid/misspelled
addresses, parts of valid or invalid addresses, or no address
information at all. What I want is: extract as much address information
as possible while keeping the number of requests small. The general case
would perhaps be a probability distribution of locations for each zoom
level, or probabilities for (a location to be within) a set of
(disjunct) regions, where regions could be continents, countries,
quarters of cities, or any other regions on any reasonable scale.

This involves reverse requests, too, because if I have found a location
possibly matching the text string, I want to get the correct address at
this location to assess text similarity. And I want to know which parts
of the text do probably contain which part of the found address.

Most of this will go to nominatim/addressminer.py. I also want to allow
for other location information (such as inferred from the language
(which is already part of Nominatim, but the module currently only
allows for one language, not an iterable, which I'd like to change some
time), or from other information provided externally (like by other text
miners)).

If you think that doesn't fit into your module, let me know. I also had
some doubt, but in order to extract maximal address information, the
miner should know the data structures of the geocoder very well.

best,
ibu

> 2014-07-10 12:43 GMT+02:00 iburadempa notifications@github.com:
> 
> > hi damian,
> > 
> > do you have plans for further improvement of the nominatim module?
> > 
> > in my view it would be nice to have functions for extracting useful
> > information from the query results, in particular if there are many of
> > them.

**Pull request merged**
